//
//  PaintCodeImages.h
//  Snapoll
//
//  Created by Richard Lichkus on 7/13/14.
//  Copyright (c) 2014 CleverKnot LLC. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface PaintCodeImages : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas1Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* circleXIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* circlePlusIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* circlePlusTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* circleXBadgeTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* circleLeftBackArrowTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* emailSymbolTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* facebookSymbolTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* twitterSymbolTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* loginBackgroundTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* bBPlaceholderAvatarTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas2Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* circlePlusIconHighlightedTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* facebookLoginTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* twitterLoginTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* emailLoginTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* loginLockTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* loginSliderTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* profileBackgroundTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* eventIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* pollIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* addIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* minusIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* circleRightBackArrowTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* editTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* clockTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* locationPinTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* personTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* questionMarkTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* openLockTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* closedLockTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* radioTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* selectedRadioTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* checkBoxTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* selectedCheckBoxTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* speedDialTargets;

// Colors
+ (UIColor*)snapollGreen;
+ (UIColor*)snapollHighlightGreen;
+ (UIColor*)snapollSelectedGreen;
+ (UIColor*)loginSelectedBlue;
+ (UIColor*)loginNormalBlue;

// Images
+ (UIImage*)bird_blue_48;
+ (UIImage*)fBfLogoBluebroadcast;

// Drawing Methods
+ (void)drawCanvas1;
+ (void)drawCircleXIcon;
+ (void)drawCirclePlusIconWithSelected: (BOOL)selected;
+ (void)drawCircleBackArrowIcon;
+ (void)drawTrashCan;
+ (void)drawEnvelopeBadges;
+ (void)drawCirclePlus;
+ (void)drawCircleXBadge;
+ (void)drawSemiCircleSlideIndicatorIcon;
+ (void)drawHorizontalHollowSlideIndicator;
+ (void)drawHorizontalSlideIndicator;
+ (void)drawVerticalHollowSlideIndicator;
+ (void)drawVerticalSolidSlideIndicator;
+ (void)drawCircleLeftBackArrow;
+ (void)drawEmailSymbol;
+ (void)drawFacebookSymbol;
+ (void)drawTwitterSymbol;
+ (void)drawBBPlaceholderAvatar;
+ (void)drawCanvas2;
+ (void)drawCirclePlusIconSelected;
+ (void)drawCirclePlusIconHighlighted;
+ (void)drawSegmentedLoginWithSelectedSegment: (CGFloat)selectedSegment;
+ (void)drawFacebookLoginWithSelected: (BOOL)selected;
+ (void)drawTwitterLoginWithSelected: (BOOL)selected;
+ (void)drawEmailLoginWithSelected: (BOOL)selected;
+ (void)drawLoginLockWithLockRotation: (CGFloat)lockRotation;
+ (void)drawLoginSliderWithSelected: (BOOL)selected;
+ (void)drawProfileBackground;
+ (void)drawEventIcon;
+ (void)drawPollIcon;
+ (void)drawAddIcon;
+ (void)drawMinusIcon;
+ (void)drawCircleRightBackArrow;
+ (void)drawEdit;
+ (void)drawClock;
+ (void)drawLocationPin;
+ (void)drawPerson;
+ (void)drawQuestionMark;
+ (void)drawOpenLock;
+ (void)drawClosedLock;
+ (void)drawRadio;
+ (void)drawSelectedRadio;
+ (void)drawCheckBox;
+ (void)drawSelectedCheckBox;
+ (void)drawSpeedDial;

// Generated Images
+ (UIImage*)imageOfCanvas1;
+ (UIImage*)imageOfCircleXIcon;
+ (UIImage*)imageOfCirclePlusIconWithSelected: (BOOL)selected;
+ (UIImage*)imageOfCirclePlus;
+ (UIImage*)imageOfCircleXBadge;
+ (UIImage*)imageOfCircleLeftBackArrow;
+ (UIImage*)imageOfEmailSymbol;
+ (UIImage*)imageOfFacebookSymbol;
+ (UIImage*)imageOfTwitterSymbol;
+ (UIImage*)imageOfLoginBackground;
+ (UIImage*)imageOfBBPlaceholderAvatar;
+ (UIImage*)imageOfCanvas2;
+ (UIImage*)imageOfCirclePlusIconHighlighted;
+ (UIImage*)imageOfFacebookLoginWithSelected: (BOOL)selected;
+ (UIImage*)imageOfTwitterLoginWithSelected: (BOOL)selected;
+ (UIImage*)imageOfEmailLoginWithSelected: (BOOL)selected;
+ (UIImage*)imageOfLoginLockWithLockRotation: (CGFloat)lockRotation;
+ (UIImage*)imageOfLoginSliderWithSelected: (BOOL)selected;
+ (UIImage*)imageOfProfileBackground;
+ (UIImage*)imageOfEventIcon;
+ (UIImage*)imageOfPollIcon;
+ (UIImage*)imageOfAddIcon;
+ (UIImage*)imageOfMinusIcon;
+ (UIImage*)imageOfCircleRightBackArrow;
+ (UIImage*)imageOfEdit;
+ (UIImage*)imageOfClock;
+ (UIImage*)imageOfLocationPin;
+ (UIImage*)imageOfPerson;
+ (UIImage*)imageOfQuestionMark;
+ (UIImage*)imageOfOpenLock;
+ (UIImage*)imageOfClosedLock;
+ (UIImage*)imageOfRadio;
+ (UIImage*)imageOfSelectedRadio;
+ (UIImage*)imageOfCheckBox;
+ (UIImage*)imageOfSelectedCheckBox;
+ (UIImage*)imageOfSpeedDial;

@end
